name: CI - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: devops-shop/roboshop-github-actions/.github/workflows/ci-mains.yml@main
    with:
      appType: 'angular'
      appName: 'frontend'
    secrets:
      vault_token: ${{ secrets.vault_token }}